# permissions for end users to view maths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: math-viewer-role
rules:
- apiGroups:
  - math.example.com
  resources:
  - maths
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - math.example.com
  resources:
  - maths/status
  verbs:
  - get
